services:
  boundary-game:
    build:
      context: .
      dockerfile: Dockerfile
    image: boundary-game:latest
    container_name: boundary-game
    ports:
      - "3213:3000"  # Node.js服务器 (HTTP + WebSocket)
    restart: unless-stopped
    networks:
      - boundary-network
    # Unraid 推荐配置
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  boundary-network:
    driver: bridge

