services:
  boundary-game:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: boundary-game:latest
    container_name: boundary-game
    ports:
      - "8880:8080"  # 静态文件服务器
      - "3001:3001"  # WebSocket 服务器
    restart: unless-stopped
    environment:
      - WS_PORT=3001
      - NODE_ENV=production
    networks:
      - boundary-network
    # Unraid 推荐配置
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  boundary-network:
    driver: bridge

